[2024-12-12T14:46:46.402-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-12T14:46:46.413-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: medallion_architecture.passo1 manual__2024-12-12T17:46:05.204232+00:00 [queued]>
[2024-12-12T14:46:46.420-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: medallion_architecture.passo1 manual__2024-12-12T17:46:05.204232+00:00 [queued]>
[2024-12-12T14:46:46.420-0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-12-12T14:46:46.467-0300] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): passo1> on 2024-12-12 17:46:05.204232+00:00
[2024-12-12T14:46:46.474-0300] {standard_task_runner.py:63} INFO - Started process 174389 to run task
[2024-12-12T14:46:46.474-0300] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-12-12T14:46:46.479-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'medallion_architecture', 'passo1', 'manual__2024-12-12T17:46:05.204232+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmp5yjxo0xl']
[2024-12-12T14:46:46.480-0300] {standard_task_runner.py:91} INFO - Job 153: Subtask passo1
[2024-12-12T14:46:46.511-0300] {task_command.py:426} INFO - Running <TaskInstance: medallion_architecture.passo1 manual__2024-12-12T17:46:05.204232+00:00 [running]> on host beatriz-linux
[2024-12-12T14:46:46.574-0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='medallion_architecture' AIRFLOW_CTX_TASK_ID='passo1' AIRFLOW_CTX_EXECUTION_DATE='2024-12-12T17:46:05.204232+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-12T17:46:05.204232+00:00'
[2024-12-12T14:46:46.575-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-12T14:46:46.576-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-12T14:46:46.576-0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/beatriz/Documentos/airflow/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/beatriz/Documentos/airflow/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/beatriz/Documentos/airflow/airflow_venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/beatriz/Documentos/airflow/airflow_venv/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/beatriz/Documentos/airflow/airflow_venv/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: passo1_bronze() missing 1 required positional argument: 'spark'
[2024-12-12T14:46:46.584-0300] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=medallion_architecture, task_id=passo1, execution_date=20241212T174605, start_date=20241212T174646, end_date=20241212T174646
[2024-12-12T14:46:46.595-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 153 for task passo1 (passo1_bronze() missing 1 required positional argument: 'spark'; 174389)
[2024-12-12T14:46:46.610-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-12-12T14:46:46.627-0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-12T14:46:46.633-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
