[2024-12-12T11:00:33.479-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-12T11:00:33.489-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: medallion_architecture.spark_submit manual__2024-12-12T14:00:22.970665+00:00 [queued]>
[2024-12-12T11:00:33.495-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: medallion_architecture.spark_submit manual__2024-12-12T14:00:22.970665+00:00 [queued]>
[2024-12-12T11:00:33.495-0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-12-12T11:00:33.510-0300] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): spark_submit> on 2024-12-12 14:00:22.970665+00:00
[2024-12-12T11:00:33.524-0300] {standard_task_runner.py:63} INFO - Started process 67112 to run task
[2024-12-12T11:00:33.524-0300] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-12-12T11:00:33.528-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'medallion_architecture', 'spark_submit', 'manual__2024-12-12T14:00:22.970665+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmp7v7k_ba1']
[2024-12-12T11:00:33.529-0300] {standard_task_runner.py:91} INFO - Job 131: Subtask spark_submit
[2024-12-12T11:00:33.560-0300] {task_command.py:426} INFO - Running <TaskInstance: medallion_architecture.spark_submit manual__2024-12-12T14:00:22.970665+00:00 [running]> on host beatriz-linux
[2024-12-12T11:00:33.624-0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='medallion_architecture' AIRFLOW_CTX_TASK_ID='spark_submit' AIRFLOW_CTX_EXECUTION_DATE='2024-12-12T14:00:22.970665+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-12T14:00:22.970665+00:00'
[2024-12-12T11:00:33.625-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-12T11:00:33.626-0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-12T11:00:33.626-0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '"\n    export AWS_ACCESS_KEY_ID=ASIAWAA66KBXXMU7KCLM;\n    export AWS_SECRET_ACCESS_KEY=***;\n    export AWS_SESSION_TOKEN=***;\n    /opt/spark/bin/spark-submit         --packages org.apache.hadoop:hadoop-aws:3.3.4,com.amazonaws:aws-java-sdk-bundle:1.12.508         --conf spark.hadoop.fs.s3a.aws.credentials.provider=com.amazonaws.auth.DefaultAWSCredentialsProviderChain         --conf spark.hadoop.fs.s3a.endpoint=s3.amazonaws.com         --conf spark.hadoop.fs.s3a.region=us-east-1         s3a://bw-airflow/lakehouse\n    ']
[2024-12-12T11:00:33.639-0300] {subprocess.py:86} INFO - Output:
[2024-12-12T11:00:33.645-0300] {subprocess.py:93} INFO - /usr/bin/bash: -c: linha 1: encontrado EOF inesperado enquanto procurava por `"' correspondente
[2024-12-12T11:00:33.645-0300] {subprocess.py:93} INFO - /usr/bin/bash: -c: linha 7: erro de sintaxe: fim prematuro do arquivo
[2024-12-12T11:00:33.646-0300] {subprocess.py:97} INFO - Command exited with return code 2
[2024-12-12T11:00:33.646-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-12T11:00:33.654-0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/beatriz/Documentos/airflow/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/beatriz/Documentos/airflow/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/beatriz/Documentos/airflow/airflow_venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/beatriz/Documentos/airflow/airflow_venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-12-12T11:00:33.658-0300] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=medallion_architecture, task_id=spark_submit, execution_date=20241212T140022, start_date=20241212T140033, end_date=20241212T140033
[2024-12-12T11:00:33.673-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 131 for task spark_submit (Bash command failed. The command returned a non-zero exit code 2.; 67112)
[2024-12-12T11:00:33.699-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-12-12T11:00:33.728-0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-12T11:00:33.736-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
