[2024-12-11T17:19:45.888-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-11T17:19:45.898-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: medallion_architecture.passo1 manual__2024-12-11T20:19:41.536404+00:00 [queued]>
[2024-12-11T17:19:45.906-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: medallion_architecture.passo1 manual__2024-12-11T20:19:41.536404+00:00 [queued]>
[2024-12-11T17:19:45.907-0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-12-11T17:19:45.921-0300] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): passo1> on 2024-12-11 20:19:41.536404+00:00
[2024-12-11T17:19:45.926-0300] {standard_task_runner.py:63} INFO - Started process 8736 to run task
[2024-12-11T17:19:45.929-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'medallion_architecture', 'passo1', 'manual__2024-12-11T20:19:41.536404+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmpgd2ztpty']
[2024-12-11T17:19:45.930-0300] {standard_task_runner.py:91} INFO - Job 61: Subtask passo1
[2024-12-11T17:19:45.960-0300] {task_command.py:426} INFO - Running <TaskInstance: medallion_architecture.passo1 manual__2024-12-11T20:19:41.536404+00:00 [running]> on host beatriz-linux
[2024-12-11T17:19:46.019-0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='medallion_architecture' AIRFLOW_CTX_TASK_ID='passo1' AIRFLOW_CTX_EXECUTION_DATE='2024-12-11T20:19:41.536404+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-11T20:19:41.536404+00:00'
[2024-12-11T17:19:46.020-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-11T17:19:46.021-0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-11T17:19:46.021-0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --packages org.apache.hadoop:hadoop-aws:3.3.4 --conf spark.hadoop.fs.s3a.access.key=YOUR_ACCESS_KEY --conf spark.hadoop.fs.s3a.secret.key=YOUR_SECRET_KEY --conf spark.hadoop.fs.s3a.endpoint=s3.amazonaws.com  /home/beatriz/Documentos/airflow/dags/tarefas/passo1_bronze.py']
[2024-12-11T17:19:46.029-0300] {subprocess.py:86} INFO - Output:
[2024-12-11T17:19:48.008-0300] {subprocess.py:93} INFO - 24/12/11 17:19:48 WARN Utils: Your hostname, beatriz-linux resolves to a loopback address: 127.0.1.1; using 192.168.7.5 instead (on interface wlp0s20f3)
[2024-12-11T17:19:48.011-0300] {subprocess.py:93} INFO - 24/12/11 17:19:48 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2024-12-11T17:19:48.263-0300] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/home/beatriz/Documentos/airflow/airflow_venv/lib/python3.10/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-12-11T17:19:48.366-0300] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/beatriz/.ivy2/cache
[2024-12-11T17:19:48.367-0300] {subprocess.py:93} INFO - The jars for the packages stored in: /home/beatriz/.ivy2/jars
[2024-12-11T17:19:48.371-0300] {subprocess.py:93} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2024-12-11T17:19:48.372-0300] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-458e61a0-b39f-4c89-9b05-978f3233f63f;1.0
[2024-12-11T17:19:48.373-0300] {subprocess.py:93} INFO - 	confs: [default]
[2024-12-11T17:19:48.547-0300] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-aws;3.3.4 in central
[2024-12-11T17:19:48.571-0300] {subprocess.py:93} INFO - 	found com.amazonaws#aws-java-sdk-bundle;1.12.262 in central
[2024-12-11T17:19:48.595-0300] {subprocess.py:93} INFO - 	found org.wildfly.openssl#wildfly-openssl;1.0.7.Final in central
[2024-12-11T17:19:48.613-0300] {subprocess.py:93} INFO - :: resolution report :: resolve 232ms :: artifacts dl 8ms
[2024-12-11T17:19:48.613-0300] {subprocess.py:93} INFO - 	:: modules in use:
[2024-12-11T17:19:48.614-0300] {subprocess.py:93} INFO - 	com.amazonaws#aws-java-sdk-bundle;1.12.262 from central in [default]
[2024-12-11T17:19:48.614-0300] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-aws;3.3.4 from central in [default]
[2024-12-11T17:19:48.614-0300] {subprocess.py:93} INFO - 	org.wildfly.openssl#wildfly-openssl;1.0.7.Final from central in [default]
[2024-12-11T17:19:48.614-0300] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-12-11T17:19:48.614-0300] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2024-12-11T17:19:48.614-0300] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2024-12-11T17:19:48.614-0300] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-12-11T17:19:48.615-0300] {subprocess.py:93} INFO - 	|      default     |   3   |   0   |   0   |   0   ||   3   |   0   |
[2024-12-11T17:19:48.615-0300] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-12-11T17:19:48.617-0300] {subprocess.py:93} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-458e61a0-b39f-4c89-9b05-978f3233f63f
[2024-12-11T17:19:48.618-0300] {subprocess.py:93} INFO - 	confs: [default]
[2024-12-11T17:19:48.623-0300] {subprocess.py:93} INFO - 	0 artifacts copied, 3 already retrieved (0kB/5ms)
[2024-12-11T17:19:49.181-0300] {subprocess.py:93} INFO - python3: can't open file '/home/beatriz/Documentos/airflow/dags/tarefas/passo1_bronze.py': [Errno 2] No such file or directory
[2024-12-11T17:19:49.191-0300] {subprocess.py:93} INFO - 24/12/11 17:19:49 INFO ShutdownHookManager: Shutdown hook called
[2024-12-11T17:19:49.192-0300] {subprocess.py:93} INFO - 24/12/11 17:19:49 INFO ShutdownHookManager: Deleting directory /tmp/spark-1472c7d4-99dc-4e1d-a501-c470c76ca7d8
[2024-12-11T17:19:49.235-0300] {subprocess.py:97} INFO - Command exited with return code 2
[2024-12-11T17:19:49.236-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-11T17:19:49.241-0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/beatriz/Documentos/airflow/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/beatriz/Documentos/airflow/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/beatriz/Documentos/airflow/airflow_venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/beatriz/Documentos/airflow/airflow_venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-12-11T17:19:49.244-0300] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=medallion_architecture, task_id=passo1, execution_date=20241211T201941, start_date=20241211T201945, end_date=20241211T201949
[2024-12-11T17:19:49.254-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 61 for task passo1 (Bash command failed. The command returned a non-zero exit code 2.; 8736)
[2024-12-11T17:19:49.269-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-12-11T17:19:49.283-0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-11T17:19:49.290-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
