[2024-12-11T17:23:30.505-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-11T17:23:30.516-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: medallion_architecture.passo1 manual__2024-12-11T20:23:27.091636+00:00 [queued]>
[2024-12-11T17:23:30.520-0300] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: medallion_architecture.passo1 manual__2024-12-11T20:23:27.091636+00:00 [queued]>
[2024-12-11T17:23:30.521-0300] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-12-11T17:23:30.533-0300] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): passo1> on 2024-12-11 20:23:27.091636+00:00
[2024-12-11T17:23:30.536-0300] {standard_task_runner.py:63} INFO - Started process 10035 to run task
[2024-12-11T17:23:30.539-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'medallion_architecture', 'passo1', 'manual__2024-12-11T20:23:27.091636+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmpsxrbmkns']
[2024-12-11T17:23:30.540-0300] {standard_task_runner.py:91} INFO - Job 64: Subtask passo1
[2024-12-11T17:23:30.575-0300] {task_command.py:426} INFO - Running <TaskInstance: medallion_architecture.passo1 manual__2024-12-11T20:23:27.091636+00:00 [running]> on host beatriz-linux
[2024-12-11T17:23:30.632-0300] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='medallion_architecture' AIRFLOW_CTX_TASK_ID='passo1' AIRFLOW_CTX_EXECUTION_DATE='2024-12-11T20:23:27.091636+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-11T20:23:27.091636+00:00'
[2024-12-11T17:23:30.633-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-11T17:23:30.633-0300] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-11T17:23:30.634-0300] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --packages org.apache.hadoop:hadoop-aws:3.3.4 --conf spark.hadoop.fs.s3a.access.key=ASIAWAA66KBX2ONRRMAT --conf spark.hadoop.fs.s3a.secret.key=VfHaOQRx2Zcm2Y00e8o49kBOnXhdV+qZBLvKWbln --conf spark.hadoop.fs.s3a.endpoint=s3.amazonaws.com  /home/beatriz/Documentos/airflow/dags/tarefas/passo1_bronze.py']
[2024-12-11T17:23:30.642-0300] {subprocess.py:86} INFO - Output:
[2024-12-11T17:23:32.414-0300] {subprocess.py:93} INFO - 24/12/11 17:23:32 WARN Utils: Your hostname, beatriz-linux resolves to a loopback address: 127.0.1.1; using 192.168.7.5 instead (on interface wlp0s20f3)
[2024-12-11T17:23:32.416-0300] {subprocess.py:93} INFO - 24/12/11 17:23:32 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2024-12-11T17:23:32.645-0300] {subprocess.py:93} INFO - :: loading settings :: url = jar:file:/home/beatriz/Documentos/airflow/airflow_venv/lib/python3.10/site-packages/pyspark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2024-12-11T17:23:32.745-0300] {subprocess.py:93} INFO - Ivy Default Cache set to: /home/beatriz/.ivy2/cache
[2024-12-11T17:23:32.746-0300] {subprocess.py:93} INFO - The jars for the packages stored in: /home/beatriz/.ivy2/jars
[2024-12-11T17:23:32.750-0300] {subprocess.py:93} INFO - org.apache.hadoop#hadoop-aws added as a dependency
[2024-12-11T17:23:32.750-0300] {subprocess.py:93} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-f90f0e32-4530-4c72-9018-1fb6c1cf606f;1.0
[2024-12-11T17:23:32.751-0300] {subprocess.py:93} INFO - 	confs: [default]
[2024-12-11T17:23:32.902-0300] {subprocess.py:93} INFO - 	found org.apache.hadoop#hadoop-aws;3.3.4 in central
[2024-12-11T17:23:32.927-0300] {subprocess.py:93} INFO - 	found com.amazonaws#aws-java-sdk-bundle;1.12.262 in central
[2024-12-11T17:23:32.947-0300] {subprocess.py:93} INFO - 	found org.wildfly.openssl#wildfly-openssl;1.0.7.Final in central
[2024-12-11T17:23:32.963-0300] {subprocess.py:93} INFO - :: resolution report :: resolve 206ms :: artifacts dl 7ms
[2024-12-11T17:23:32.964-0300] {subprocess.py:93} INFO - 	:: modules in use:
[2024-12-11T17:23:32.964-0300] {subprocess.py:93} INFO - 	com.amazonaws#aws-java-sdk-bundle;1.12.262 from central in [default]
[2024-12-11T17:23:32.964-0300] {subprocess.py:93} INFO - 	org.apache.hadoop#hadoop-aws;3.3.4 from central in [default]
[2024-12-11T17:23:32.964-0300] {subprocess.py:93} INFO - 	org.wildfly.openssl#wildfly-openssl;1.0.7.Final from central in [default]
[2024-12-11T17:23:32.965-0300] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-12-11T17:23:32.965-0300] {subprocess.py:93} INFO - 	|                  |            modules            ||   artifacts   |
[2024-12-11T17:23:32.965-0300] {subprocess.py:93} INFO - 	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
[2024-12-11T17:23:32.965-0300] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-12-11T17:23:32.965-0300] {subprocess.py:93} INFO - 	|      default     |   3   |   0   |   0   |   0   ||   3   |   0   |
[2024-12-11T17:23:32.965-0300] {subprocess.py:93} INFO - 	---------------------------------------------------------------------
[2024-12-11T17:23:32.967-0300] {subprocess.py:93} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-f90f0e32-4530-4c72-9018-1fb6c1cf606f
[2024-12-11T17:23:32.968-0300] {subprocess.py:93} INFO - 	confs: [default]
[2024-12-11T17:23:32.972-0300] {subprocess.py:93} INFO - 	0 artifacts copied, 3 already retrieved (0kB/5ms)
[2024-12-11T17:23:33.519-0300] {subprocess.py:93} INFO - python3: can't open file '/home/beatriz/Documentos/airflow/dags/tarefas/passo1_bronze.py': [Errno 2] No such file or directory
[2024-12-11T17:23:33.530-0300] {subprocess.py:93} INFO - 24/12/11 17:23:33 INFO ShutdownHookManager: Shutdown hook called
[2024-12-11T17:23:33.530-0300] {subprocess.py:93} INFO - 24/12/11 17:23:33 INFO ShutdownHookManager: Deleting directory /tmp/spark-e8753f3b-d2e9-4195-ae7f-b04e403a1508
[2024-12-11T17:23:33.569-0300] {subprocess.py:97} INFO - Command exited with return code 2
[2024-12-11T17:23:33.570-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-11T17:23:33.575-0300] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/beatriz/Documentos/airflow/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/beatriz/Documentos/airflow/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/beatriz/Documentos/airflow/airflow_venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/beatriz/Documentos/airflow/airflow_venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-12-11T17:23:33.578-0300] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=medallion_architecture, task_id=passo1, execution_date=20241211T202327, start_date=20241211T202330, end_date=20241211T202333
[2024-12-11T17:23:33.587-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 64 for task passo1 (Bash command failed. The command returned a non-zero exit code 2.; 10035)
[2024-12-11T17:23:33.598-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-12-11T17:23:33.612-0300] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-11T17:23:33.618-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
